server:
  port: 8010

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///D://SpringCloudHelloDemo/ServiceConfig
          search-paths: /,/conf,/web

  application:
    name: HelloConfigService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
      CS: http://localhost:8100/eureka/
  instance:
    instance-id: ConfigServer
management:
  endpoints:
    web:
      exposure:
        include: '*'
