server:
  port: 8100
spring:
  application:
    name: HelloServiceCenter
  cloud:
    config:
      enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8100/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'